# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_aWZKd_QUoaSFTm5AQTJtoKIDSKaFge
"""

hes_with_rats = df1[df1['seconds_after_rat_arrival'] > 0]['bat_landing_to_food']
hes_without_rats = df1[df1['seconds_after_rat_arrival'] == 0]['bat_landing_to_food']

t_stat, p_val = stats.ttest_ind(hes_with_rats, hes_without_rats, equal_var=False)
print("\n📊 INFERENTIAL (Dataset1): T-test on Bat Hesitation With vs Without Rats")
print(f"T-statistic: {t_stat:.3f}, P-value: {p_val:.4f}")
if p_val < 0.05:
    print("✅ Significant difference → Rats influence bat hesitation behaviour.")
else:
    print("❌ No significant difference → Rats do not change bat hesitation behaviour.")


landings_with_rats = df2[df2['rat_present']]['bat_landing_number']
landings_without_rats = df2[~df2['rat_present']]['bat_landing_number']

t_stat2, p_val2 = stats.ttest_ind(landings_with_rats, landings_without_rats, equal_var=False)
print("\n📊 INFERENTIAL (Dataset2): T-test on Bat Landings With vs Without Rats")
print(f"T-statistic: {t_stat2:.3f}, P-value: {p_val2:.4f}")
if p_val2 < 0.05:
    print("✅ Significant difference → Rat presence affects bat landing frequency.")
else:
    print("❌ No significant difference → Rat presence does not affect landing frequency.")