# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_aWZKd_QUoaSFTm5AQTJtoKIDSKaFge
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

df1 = pd.read_csv('/content/dataset1(HIT140).csv')
df2 = pd.read_csv('/content/dataset2(HIT140).csv')

print("Dataset1 shape:", df1.shape)
print("Dataset2 shape:", df2.shape)

df1 = df1.dropna(subset=['habit'])

df1 = df1[df1['hours_after_sunset'] >= 0]
df2 = df2[df2['hours_after_sunset'] >= 0]

df1.reset_index(drop=True, inplace=True)
df2.reset_index(drop=True, inplace=True)

print("\n✅ Data Wrangling complete - cleaned missing values & negatives.")