# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_aWZKd_QUoaSFTm5AQTJtoKIDSKaFge
"""

def descriptive_stats(df, name):
    print(f"\n===== DESCRIPTIVE STATISTICS for {name} =====")
    numeric_cols = df.select_dtypes(include='number').columns
    for col in numeric_cols:
        print(f"\n--- {col} ---")
        print(f"Mean: {df[col].mean():.2f}")
        print(f"Median: {df[col].median():.2f}")
        print(f"Mode: {df[col].mode()[0]}")
        print(f"Std Dev: {df[col].std():.2f}")
        print(f"Variance: {df[col].var():.2f}")
        print(f"IQR: {df[col].quantile(0.75) - df[col].quantile(0.25):.2f}")

descriptive_stats(df1, "Dataset1 (Bat hesitation & risk behaviour)")
descriptive_stats(df2, "Dataset2 (Bat activity & rat presence)")


plt.figure(figsize=(8,5))
sns.histplot(df1['bat_landing_to_food'], bins=30, kde=True, color='blue')
plt.title("DESCRIPTIVE: Dataset1 - Distribution of Bat Hesitation Time")
plt.xlabel("Seconds between landing and food approach")
plt.show()
print("\n📊 Descriptive (Dataset1): Histogram shows the distribution of bat hesitation time.")


plt.figure(figsize=(8,5))
sns.boxplot(x=df1['risk'], y=df1['bat_landing_to_food'], palette="Set2")
plt.xticks([0,1], ["Risk Avoidance","Risk Taking"])
plt.title("DESCRIPTIVE: Dataset1 - Hesitation vs Risk-taking")
plt.ylabel("Hesitation Time (seconds)")
plt.show()
print("\n📊 Descriptive (Dataset1): Boxplot compares hesitation when bats take risk vs avoid risk.")


df2['rat_present'] = df2['rat_minutes'] > 0
plt.figure(figsize=(8,6))
sns.boxplot(x='rat_present', y='bat_landing_number', data=df2, palette='coolwarm')
plt.xticks([0,1], ["No Rats","Rats Present"])
plt.title("DESCRIPTIVE: Dataset2 - Bat Landings vs Rat Presence")
plt.ylabel("Number of Bat Landings")
plt.show()
print("\n📊 Descriptive (Dataset2): Boxplot compares bat landing frequency with vs without rats.")