# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_aWZKd_QUoaSFTm5AQTJtoKIDSKaFge
"""

sample_means = []
for i in range(1000):
    sample = df2['bat_landing_number'].sample(50, replace=True)
    sample_means.append(sample.mean())

plt.figure(figsize=(8,6))
sns.histplot(sample_means, bins=30, kde=True, color='purple')
plt.title("INFERENTIAL: Dataset2 - Central Limit Theorem (Sample Means)")
plt.xlabel("Sample Mean of Bat Landings (n=50)")
plt.show()
print("\n📊 Inferential (Dataset2): CLT → Repeated samples show normal-like distribution of bat landing means.")