# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K_aWZKd_QUoaSFTm5AQTJtoKIDSKaFge
"""

corr, p_corr = stats.pearsonr(df2['rat_minutes'], df2['bat_landing_number'])
print(f"\n📊 INFERENTIAL (Dataset2): Correlation between Rat Minutes and Bat Landings: {corr:.3f}, P-value: {p_corr:.4f}")
if p_corr < 0.05:
    if corr < 0:
        print("✅ Negative correlation → More rat activity = fewer bat landings.")
    else:
        print("✅ Positive correlation → More rat activity = more bat landings.")
else:
    print("❌ No significant correlation between rat activity and bat landings.")